version: "2"
services:
  mongo:
    image: mongo
    networks:
      - chatbotnetwork
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - rasa_data:/data/db

  rasa_train:
    build: .
    image: rasa
    networks:
      - chatbotnetwork
    container_name: rasa_train
    hostname: rasa_train
    volumes:
      - rasa_training:/app/models
      - rasa_logs:/app/logs
    command: "train --verbose --debug --fixed-model-name rasa-model --domain domains"
  
  rasa:
    image: rasa
    networks:
      - chatbotnetwork
    container_name: rasa
    hostname: rasa
    links:
      - mongo
    depends_on:
      - mongo
      - action_server
      - duckling
      - dummy_rest
    ports:
      - 5005:5005
    volumes:
      - rasa_training:/app/models
      - rasa_logs:/app/logs

  action_server:
    image: rasa
    networks:
      - chatbotnetwork
    container_name: action_server
    hostname: action_server
    environment:
      - SHAREPOINT_URL=http://dummy_rest:8080
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "5055:5055"
    command: "run actions"

  x_server:
    image: rasa
    networks:
      - chatbotnetwork
    container_name: x_server
    hostname: x_server
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "5002:5002"
    command: "x"

  dummy_rest:
    build: dummy_rest/.
    image: dummy_rest
    networks:
      - chatbotnetwork
    container_name: dummy_rest
    hostname: dummy_rest
    ports:
      - "80:80"

  duckling:
    image: rasa/duckling:latest
    networks:
      - chatbotnetwork
    container_name: duckling
    hostname: duckling
    ports:
      - "8000:8000"

networks:
  chatbotnetwork:

volumes:
  rasa_data:
  rasa_training:
  rasa_logs:
